"""empty message

Revision ID: d6d667a6abe5
Revises: 8772e511a760
Create Date: 2023-02-23 20:57:14.564489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d667a6abe5'
down_revision = '8772e511a760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joke', schema=None) as batch_op:
        batch_op.drop_constraint('joke_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joke', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('joke_user_id_fkey', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
